def test():
    #ERROR:
    foo(11)

    foo(3)
